# 服务容器入口
services:
  # nacos 服务发现中间件
  nacos:
    image: nacos/nacos-server:v2.2.3 # 镜像及版本
    container_name: nacos # 容器名称
    environment:
      - MODE=standalone # 单机模式(非集群)
      - NACOS_AUTH_ENABLE=false # 关闭认证，方便开发测试
    ports:
      - "8848:8848"  # HTTP端口,访问控制台用
      - "9848:9848"  # gRPC端口,Nacos 2.x 客户端与服务端通信
    volumes:
      - ./nacos/logs:/home/nacos/logs # 隐射日志到宿主机 ./nacos/logs
    restart: always # 容器退出时总是重启

  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
     - "6379:6379"
    restart: always

  # RabbitMQ 消息队列
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
     - "5672:5672"                        # AMQP 协议端口，Java/Python 客户端连接用
     - "15672:15672"                      # HTTP 管理界面端口
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  # 搜索引擎
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node         # 单节点模式，无需集群发现
      - xpack.security.enabled=false       # 关闭安全认证，开发环境方便调用
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # 限制 JVM 堆内存，避免占用过多资源
    ports:
      - "9200:9200"                        # HTTP API 端口
    restart: always

  # 任务调度平台
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: xxl-job
    ports:
      - "8088:8080"                        # 将宿主机的 8088 映射到容器的 8080（调度中心网页端口）
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
               --spring.datasource.username=root
               --spring.datasource.password=123456"
    depends_on:
      - mysql                              # 等待 mysql 容器启动后再启动本容器
    restart: always

  # 监控
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # 挂载自定义配置
    restart: always

  # grafana:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always

  # 链路追踪
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: always