server:
  port: 8085

spring:
  application:
    name: plan-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: dev
        group: DEFAULT_GROUP


management:
  endpoints:
    web:
      exposure:
        include: "*"


#logging:
#  level:
#    com.alibaba.nacos: DEBUG