server:
  port: 8083

spring:
  application:
    name: plan-task
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: dev
        group: DEFAULT_GROUP


management:
  endpoints:
    web:
      exposure:
        include: "*"


#logging:
#  level:
#    com.alibaba.nacos: DEBUG